[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/',
	'@openzeppelin/=lib/openzeppelin-contracts/',
	'@uniswap-v2-core/=lib/v2-core/',
	'@uniswap-v2-periphery/=lib/v2-periphery/'
]

gas_reports = ["*"]

# A list of ignored solc error codes

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false
# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.12'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config